"""
Password hashing and verification utilities.
"""

from pwdlib import PasswordHash
from pwdlib.exceptions import UnknownHashError

_password_hash = PasswordHash.recommended()


def hash_password(password: str) -> str:
    """
    Hash a password using pwdlib.

    Uses pwdlib with a randomly generated salt to securely hash passwords.
    The resulting hash includes the salt and can be stored directly in the database.

    Args:
        password: Plain text password to hash

    Returns:
        pwdlib hash string containing the salt and hashed password.
        This hash should be stored in the database for password verification.

    Example:
        >>> hashed = hash_password("my_password")
        >>> check_password("my_password", hashed)
        True
    """
    return _password_hash.hash(password)


def check_password(password: str, hash: str) -> bool:
    """
    Verify if a password matches a pwdlib hash.

    Compares a plain text password against a previously hashed password
    to determine if they match. Uses constant-time comparison to prevent
    timing attacks.

    Args:
        password: Plain text password to verify
        hash: pwdlib hash string (previously generated by hash_password)

    Returns:
        True if the password matches the hash, False otherwise

    Example:
        >>> stored_hash = hash_password("my_password")
        >>> check_password("my_password", stored_hash)
        True
        >>> check_password("wrong_password", stored_hash)
        False
    """
    password_bytes = password.encode("utf-8")
    hash_bytes = hash.encode("utf-8")
    try:
        return _password_hash.verify(password_bytes, hash_bytes)
    except UnknownHashError:
        return False
