"""init

Revision ID: 31e7a71b93c7
Revises:
Create Date: 2025-11-30 20:46:00.297790

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "31e7a71b93c7"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "categories",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("is_default", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_categories_created_at"), "categories", ["created_at"], unique=False)
    op.create_index(op.f("ix_categories_name"), "categories", ["name"], unique=True)
    op.create_index(op.f("ix_categories_updated_at"), "categories", ["updated_at"], unique=False)

    # Setup path for seeding imports
    import sys
    from pathlib import Path

    alembic_dir = Path(__file__).parent.parent
    if str(alembic_dir) not in sys.path:
        sys.path.insert(0, str(alembic_dir))

    # Seed default categories
    from seeding import seed_categories

    seed_categories()
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("avatar", sa.String(length=500), nullable=True),
        sa.Column("password", sa.String(length=255), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_created_at"), "users", ["created_at"], unique=False)
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_index(op.f("ix_users_updated_at"), "users", ["updated_at"], unique=False)
    op.create_table(
        "account_link_requests",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("request_token", sa.String(length=255), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("identity_provider", sa.String(length=50), nullable=False),
        sa.Column("external_id", sa.String(length=255), nullable=False),
        sa.Column("external_email", sa.String(length=255), nullable=True),
        sa.Column("external_username", sa.String(length=255), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_account_link_requests_created_at"), "account_link_requests", ["created_at"], unique=False)
    op.create_index(op.f("ix_account_link_requests_expires_at"), "account_link_requests", ["expires_at"], unique=False)
    op.create_index(
        op.f("ix_account_link_requests_request_token"), "account_link_requests", ["request_token"], unique=True
    )
    op.create_index(op.f("ix_account_link_requests_status"), "account_link_requests", ["status"], unique=False)
    op.create_index(op.f("ix_account_link_requests_updated_at"), "account_link_requests", ["updated_at"], unique=False)
    op.create_index(op.f("ix_account_link_requests_user_id"), "account_link_requests", ["user_id"], unique=False)
    op.create_index("ix_link_request_expires", "account_link_requests", ["expires_at"], unique=False)
    op.create_index("ix_link_request_status", "account_link_requests", ["status"], unique=False)
    op.create_index("ix_link_request_token", "account_link_requests", ["request_token"], unique=False)
    op.create_index("ix_link_request_user", "account_link_requests", ["user_id"], unique=False)
    op.create_table(
        "groups",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.Column("updated_by", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["updated_by"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_groups_created_at"), "groups", ["created_at"], unique=False)
    op.create_index(op.f("ix_groups_created_by"), "groups", ["created_by"], unique=False)
    op.create_index(op.f("ix_groups_updated_at"), "groups", ["updated_at"], unique=False)
    op.create_index(op.f("ix_groups_updated_by"), "groups", ["updated_by"], unique=False)
    op.create_table(
        "refresh_tokens",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("device_info", sa.String(length=255), nullable=True),
        sa.Column("is_revoked", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_refresh_token_user_revoked", "refresh_tokens", ["user_id", "is_revoked"], unique=False)
    op.create_index(op.f("ix_refresh_tokens_created_at"), "refresh_tokens", ["created_at"], unique=False)
    op.create_index(op.f("ix_refresh_tokens_is_revoked"), "refresh_tokens", ["is_revoked"], unique=False)
    op.create_index(op.f("ix_refresh_tokens_updated_at"), "refresh_tokens", ["updated_at"], unique=False)
    op.create_index(op.f("ix_refresh_tokens_user_id"), "refresh_tokens", ["user_id"], unique=False)
    op.create_table(
        "system_role_bindings",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("role", sa.String(length=50), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", name="uq_user_system_role"),
    )
    op.create_index("ix_system_role_binding_user", "system_role_bindings", ["user_id"], unique=False)
    op.create_index(op.f("ix_system_role_bindings_role"), "system_role_bindings", ["role"], unique=False)
    op.create_index(op.f("ix_system_role_bindings_user_id"), "system_role_bindings", ["user_id"], unique=False)
    op.create_table(
        "user_identities",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("identity_provider", sa.String(length=50), nullable=False),
        sa.Column("external_id", sa.String(length=255), nullable=False),
        sa.Column("external_email", sa.String(length=255), nullable=True),
        sa.Column("external_username", sa.String(length=255), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("identity_provider", "external_id", name="uq_provider_external_id"),
    )
    op.create_index(op.f("ix_user_identities_created_at"), "user_identities", ["created_at"], unique=False)
    op.create_index(op.f("ix_user_identities_updated_at"), "user_identities", ["updated_at"], unique=False)
    op.create_index(op.f("ix_user_identities_user_id"), "user_identities", ["user_id"], unique=False)
    op.create_index("ix_user_identity_external_id", "user_identities", ["external_id"], unique=False)
    op.create_index("ix_user_identity_provider", "user_identities", ["identity_provider"], unique=False)
    op.create_index("ix_user_identity_user", "user_identities", ["user_id"], unique=False)
    op.create_table(
        "group_role_bindings",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("group_id", sa.Integer(), nullable=False),
        sa.Column("role", sa.String(length=50), nullable=False),
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.Column("updated_by", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["group_id"],
            ["groups.id"],
        ),
        sa.ForeignKeyConstraint(
            ["updated_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "group_id", name="uq_user_group_role"),
    )
    op.create_index("ix_group_role_binding_group", "group_role_bindings", ["group_id"], unique=False)
    op.create_index("ix_group_role_binding_user", "group_role_bindings", ["user_id"], unique=False)
    op.create_index(op.f("ix_group_role_bindings_created_at"), "group_role_bindings", ["created_at"], unique=False)
    op.create_index(op.f("ix_group_role_bindings_created_by"), "group_role_bindings", ["created_by"], unique=False)
    op.create_index(op.f("ix_group_role_bindings_group_id"), "group_role_bindings", ["group_id"], unique=False)
    op.create_index(op.f("ix_group_role_bindings_role"), "group_role_bindings", ["role"], unique=False)
    op.create_index(op.f("ix_group_role_bindings_updated_at"), "group_role_bindings", ["updated_at"], unique=False)
    op.create_index(op.f("ix_group_role_bindings_updated_by"), "group_role_bindings", ["updated_by"], unique=False)
    op.create_index(op.f("ix_group_role_bindings_user_id"), "group_role_bindings", ["user_id"], unique=False)
    op.create_table(
        "periods",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("group_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("start_date", sa.DateTime(timezone=True), nullable=False),
        sa.Column("end_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("closed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.Column("updated_by", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["group_id"],
            ["groups.id"],
        ),
        sa.ForeignKeyConstraint(
            ["updated_by"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_period_group_dates", "periods", ["group_id", "start_date", "end_date"], unique=False)
    op.create_index(op.f("ix_periods_created_at"), "periods", ["created_at"], unique=False)
    op.create_index(op.f("ix_periods_created_by"), "periods", ["created_by"], unique=False)
    op.create_index(op.f("ix_periods_group_id"), "periods", ["group_id"], unique=False)
    op.create_index(op.f("ix_periods_updated_at"), "periods", ["updated_at"], unique=False)
    op.create_index(op.f("ix_periods_updated_by"), "periods", ["updated_by"], unique=False)
    op.create_table(
        "settlements",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("period_id", sa.Integer(), nullable=False),
        sa.Column("payer_id", sa.Integer(), nullable=False),
        sa.Column("payee_id", sa.Integer(), nullable=False),
        sa.Column("amount", sa.Integer(), nullable=False),
        sa.Column("date_paid", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.Column("updated_by", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["payee_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["payer_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["period_id"],
            ["periods.id"],
        ),
        sa.ForeignKeyConstraint(
            ["updated_by"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_settlement_period_payer_payee", "settlements", ["period_id", "payer_id", "payee_id"], unique=False
    )
    op.create_index(op.f("ix_settlements_created_at"), "settlements", ["created_at"], unique=False)
    op.create_index(op.f("ix_settlements_created_by"), "settlements", ["created_by"], unique=False)
    op.create_index(op.f("ix_settlements_payee_id"), "settlements", ["payee_id"], unique=False)
    op.create_index(op.f("ix_settlements_payer_id"), "settlements", ["payer_id"], unique=False)
    op.create_index(op.f("ix_settlements_period_id"), "settlements", ["period_id"], unique=False)
    op.create_index(op.f("ix_settlements_updated_at"), "settlements", ["updated_at"], unique=False)
    op.create_index(op.f("ix_settlements_updated_by"), "settlements", ["updated_by"], unique=False)
    op.create_table(
        "transactions",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("transaction_kind", sa.String(length=50), nullable=False),
        sa.Column("split_kind", sa.String(length=20), nullable=True),
        sa.Column(
            "status", sa.Enum("DRAFT", "PENDING", "APPROVED", "REJECTED", name="transactionstatus"), nullable=False
        ),
        sa.Column("description", sa.String(length=1000), nullable=True),
        sa.Column("amount", sa.Integer(), nullable=False),
        sa.Column("date_incurred", sa.DateTime(timezone=True), nullable=False),
        sa.Column("payer_id", sa.Integer(), nullable=False),
        sa.Column("category_id", sa.Integer(), nullable=False),
        sa.Column("period_id", sa.Integer(), nullable=False),
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.Column("updated_by", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["categories.id"],
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["payer_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["period_id"],
            ["periods.id"],
        ),
        sa.ForeignKeyConstraint(
            ["updated_by"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_transaction_period_created", "transactions", ["period_id", "created_at"], unique=False)
    op.create_index("ix_transaction_period_payer", "transactions", ["period_id", "payer_id"], unique=False)
    op.create_index(op.f("ix_transactions_category_id"), "transactions", ["category_id"], unique=False)
    op.create_index(op.f("ix_transactions_created_at"), "transactions", ["created_at"], unique=False)
    op.create_index(op.f("ix_transactions_created_by"), "transactions", ["created_by"], unique=False)
    op.create_index(op.f("ix_transactions_payer_id"), "transactions", ["payer_id"], unique=False)
    op.create_index(op.f("ix_transactions_period_id"), "transactions", ["period_id"], unique=False)
    op.create_index(op.f("ix_transactions_status"), "transactions", ["status"], unique=False)
    op.create_index(op.f("ix_transactions_updated_at"), "transactions", ["updated_at"], unique=False)
    op.create_index(op.f("ix_transactions_updated_by"), "transactions", ["updated_by"], unique=False)
    op.create_table(
        "expense_shares",
        sa.Column("transaction_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("share_amount", sa.Integer(), nullable=True),
        sa.Column("share_percentage", sa.Float(), nullable=True),
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.Column("updated_by", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["transaction_id"],
            ["transactions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["updated_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("transaction_id", "user_id"),
    )
    op.create_index(op.f("ix_expense_shares_created_at"), "expense_shares", ["created_at"], unique=False)
    op.create_index(op.f("ix_expense_shares_created_by"), "expense_shares", ["created_by"], unique=False)
    op.create_index(op.f("ix_expense_shares_transaction_id"), "expense_shares", ["transaction_id"], unique=False)
    op.create_index(op.f("ix_expense_shares_updated_at"), "expense_shares", ["updated_at"], unique=False)
    op.create_index(op.f("ix_expense_shares_updated_by"), "expense_shares", ["updated_by"], unique=False)
    op.create_index(op.f("ix_expense_shares_user_id"), "expense_shares", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_expense_shares_user_id"), table_name="expense_shares")
    op.drop_index(op.f("ix_expense_shares_updated_by"), table_name="expense_shares")
    op.drop_index(op.f("ix_expense_shares_updated_at"), table_name="expense_shares")
    op.drop_index(op.f("ix_expense_shares_transaction_id"), table_name="expense_shares")
    op.drop_index(op.f("ix_expense_shares_created_by"), table_name="expense_shares")
    op.drop_index(op.f("ix_expense_shares_created_at"), table_name="expense_shares")
    op.drop_table("expense_shares")
    op.drop_index(op.f("ix_transactions_updated_by"), table_name="transactions")
    op.drop_index(op.f("ix_transactions_updated_at"), table_name="transactions")
    op.drop_index(op.f("ix_transactions_status"), table_name="transactions")
    op.drop_index(op.f("ix_transactions_period_id"), table_name="transactions")
    op.drop_index(op.f("ix_transactions_payer_id"), table_name="transactions")
    op.drop_index(op.f("ix_transactions_created_by"), table_name="transactions")
    op.drop_index(op.f("ix_transactions_created_at"), table_name="transactions")
    op.drop_index(op.f("ix_transactions_category_id"), table_name="transactions")
    op.drop_index("ix_transaction_period_payer", table_name="transactions")
    op.drop_index("ix_transaction_period_created", table_name="transactions")
    op.drop_table("transactions")
    op.drop_index(op.f("ix_settlements_updated_by"), table_name="settlements")
    op.drop_index(op.f("ix_settlements_updated_at"), table_name="settlements")
    op.drop_index(op.f("ix_settlements_period_id"), table_name="settlements")
    op.drop_index(op.f("ix_settlements_payer_id"), table_name="settlements")
    op.drop_index(op.f("ix_settlements_payee_id"), table_name="settlements")
    op.drop_index(op.f("ix_settlements_created_by"), table_name="settlements")
    op.drop_index(op.f("ix_settlements_created_at"), table_name="settlements")
    op.drop_index("ix_settlement_period_payer_payee", table_name="settlements")
    op.drop_table("settlements")
    op.drop_index(op.f("ix_periods_updated_by"), table_name="periods")
    op.drop_index(op.f("ix_periods_updated_at"), table_name="periods")
    op.drop_index(op.f("ix_periods_group_id"), table_name="periods")
    op.drop_index(op.f("ix_periods_created_by"), table_name="periods")
    op.drop_index(op.f("ix_periods_created_at"), table_name="periods")
    op.drop_index("ix_period_group_dates", table_name="periods")
    op.drop_table("periods")
    op.drop_index(op.f("ix_group_role_bindings_user_id"), table_name="group_role_bindings")
    op.drop_index(op.f("ix_group_role_bindings_updated_by"), table_name="group_role_bindings")
    op.drop_index(op.f("ix_group_role_bindings_updated_at"), table_name="group_role_bindings")
    op.drop_index(op.f("ix_group_role_bindings_role"), table_name="group_role_bindings")
    op.drop_index(op.f("ix_group_role_bindings_group_id"), table_name="group_role_bindings")
    op.drop_index(op.f("ix_group_role_bindings_created_by"), table_name="group_role_bindings")
    op.drop_index(op.f("ix_group_role_bindings_created_at"), table_name="group_role_bindings")
    op.drop_index("ix_group_role_binding_user", table_name="group_role_bindings")
    op.drop_index("ix_group_role_binding_group", table_name="group_role_bindings")
    op.drop_table("group_role_bindings")
    op.drop_index("ix_user_identity_user", table_name="user_identities")
    op.drop_index("ix_user_identity_provider", table_name="user_identities")
    op.drop_index("ix_user_identity_external_id", table_name="user_identities")
    op.drop_index(op.f("ix_user_identities_user_id"), table_name="user_identities")
    op.drop_index(op.f("ix_user_identities_updated_at"), table_name="user_identities")
    op.drop_index(op.f("ix_user_identities_created_at"), table_name="user_identities")
    op.drop_table("user_identities")
    op.drop_index(op.f("ix_system_role_bindings_user_id"), table_name="system_role_bindings")
    op.drop_index(op.f("ix_system_role_bindings_role"), table_name="system_role_bindings")
    op.drop_index("ix_system_role_binding_user", table_name="system_role_bindings")
    op.drop_table("system_role_bindings")
    op.drop_index(op.f("ix_refresh_tokens_user_id"), table_name="refresh_tokens")
    op.drop_index(op.f("ix_refresh_tokens_updated_at"), table_name="refresh_tokens")
    op.drop_index(op.f("ix_refresh_tokens_is_revoked"), table_name="refresh_tokens")
    op.drop_index(op.f("ix_refresh_tokens_created_at"), table_name="refresh_tokens")
    op.drop_index("ix_refresh_token_user_revoked", table_name="refresh_tokens")
    op.drop_table("refresh_tokens")
    op.drop_index(op.f("ix_groups_updated_by"), table_name="groups")
    op.drop_index(op.f("ix_groups_updated_at"), table_name="groups")
    op.drop_index(op.f("ix_groups_created_by"), table_name="groups")
    op.drop_index(op.f("ix_groups_created_at"), table_name="groups")
    op.drop_table("groups")
    op.drop_index("ix_link_request_user", table_name="account_link_requests")
    op.drop_index("ix_link_request_token", table_name="account_link_requests")
    op.drop_index("ix_link_request_status", table_name="account_link_requests")
    op.drop_index("ix_link_request_expires", table_name="account_link_requests")
    op.drop_index(op.f("ix_account_link_requests_user_id"), table_name="account_link_requests")
    op.drop_index(op.f("ix_account_link_requests_updated_at"), table_name="account_link_requests")
    op.drop_index(op.f("ix_account_link_requests_status"), table_name="account_link_requests")
    op.drop_index(op.f("ix_account_link_requests_request_token"), table_name="account_link_requests")
    op.drop_index(op.f("ix_account_link_requests_expires_at"), table_name="account_link_requests")
    op.drop_index(op.f("ix_account_link_requests_created_at"), table_name="account_link_requests")
    op.drop_table("account_link_requests")
    op.drop_index(op.f("ix_users_updated_at"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_index(op.f("ix_users_created_at"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_categories_updated_at"), table_name="categories")
    op.drop_index(op.f("ix_categories_name"), table_name="categories")
    op.drop_index(op.f("ix_categories_created_at"), table_name="categories")
    op.drop_table("categories")
    # ### end Alembic commands ###
