"""Add identity provider tables

Revision ID: 10585db74361
Revises: 5ff9f5cde268
Create Date: 2025-11-23 23:47:32.546451

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "10585db74361"
down_revision: str | Sequence[str] | None = "5ff9f5cde268"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_identities",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("identity_provider", sa.String(length=50), nullable=False),
        sa.Column("external_id", sa.String(length=255), nullable=False),
        sa.Column("external_email", sa.String(length=255), nullable=True),
        sa.Column("external_username", sa.String(length=255), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("identity_provider", "external_id", name="uq_provider_external_id"),
    )
    op.create_index(op.f("ix_user_identities_created_at"), "user_identities", ["created_at"], unique=False)
    op.create_index(op.f("ix_user_identities_updated_at"), "user_identities", ["updated_at"], unique=False)
    op.create_index(op.f("ix_user_identities_user_id"), "user_identities", ["user_id"], unique=False)
    op.create_index("ix_user_identity_external_id", "user_identities", ["external_id"], unique=False)
    op.create_index("ix_user_identity_provider", "user_identities", ["identity_provider"], unique=False)
    op.create_index("ix_user_identity_user", "user_identities", ["user_id"], unique=False)
    op.create_table(
        "account_link_requests",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("request_token", sa.String(length=255), nullable=False),
        sa.Column("user_identity_id", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("email_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_identity_id"],
            ["user_identities.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_account_link_requests_created_at"), "account_link_requests", ["created_at"], unique=False)
    op.create_index(op.f("ix_account_link_requests_expires_at"), "account_link_requests", ["expires_at"], unique=False)
    op.create_index(
        op.f("ix_account_link_requests_request_token"), "account_link_requests", ["request_token"], unique=True
    )
    op.create_index(op.f("ix_account_link_requests_status"), "account_link_requests", ["status"], unique=False)
    op.create_index(op.f("ix_account_link_requests_updated_at"), "account_link_requests", ["updated_at"], unique=False)
    op.create_index(
        op.f("ix_account_link_requests_user_identity_id"), "account_link_requests", ["user_identity_id"], unique=False
    )
    op.create_index("ix_link_request_expires", "account_link_requests", ["expires_at"], unique=False)
    op.create_index("ix_link_request_status", "account_link_requests", ["status"], unique=False)
    op.create_index("ix_link_request_token", "account_link_requests", ["request_token"], unique=False)
    op.create_index("ix_link_request_user_identity", "account_link_requests", ["user_identity_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_link_request_user_identity", table_name="account_link_requests")
    op.drop_index("ix_link_request_token", table_name="account_link_requests")
    op.drop_index("ix_link_request_status", table_name="account_link_requests")
    op.drop_index("ix_link_request_expires", table_name="account_link_requests")
    op.drop_index(op.f("ix_account_link_requests_user_identity_id"), table_name="account_link_requests")
    op.drop_index(op.f("ix_account_link_requests_updated_at"), table_name="account_link_requests")
    op.drop_index(op.f("ix_account_link_requests_status"), table_name="account_link_requests")
    op.drop_index(op.f("ix_account_link_requests_request_token"), table_name="account_link_requests")
    op.drop_index(op.f("ix_account_link_requests_expires_at"), table_name="account_link_requests")
    op.drop_index(op.f("ix_account_link_requests_created_at"), table_name="account_link_requests")
    op.drop_table("account_link_requests")
    op.drop_index("ix_user_identity_user", table_name="user_identities")
    op.drop_index("ix_user_identity_provider", table_name="user_identities")
    op.drop_index("ix_user_identity_external_id", table_name="user_identities")
    op.drop_index(op.f("ix_user_identities_user_id"), table_name="user_identities")
    op.drop_index(op.f("ix_user_identities_updated_at"), table_name="user_identities")
    op.drop_index(op.f("ix_user_identities_created_at"), table_name="user_identities")
    op.drop_table("user_identities")
    # ### end Alembic commands ###
