"""init

Revision ID: 5ff9f5cde268
Revises:
Create Date: 2025-11-21 22:15:06.831450

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5ff9f5cde268"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "categories",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("is_default", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_categories_created_at"), "categories", ["created_at"], unique=False)
    op.create_index(op.f("ix_categories_name"), "categories", ["name"], unique=True)
    op.create_index(op.f("ix_categories_updated_at"), "categories", ["updated_at"], unique=False)

    # Seed default categories
    from datetime import UTC, datetime

    from app.models import default_categories

    categories_table = sa.table(
        "categories",
        sa.column("name", sa.String),
        sa.column("is_default", sa.Boolean),
        sa.column("created_at", sa.DateTime),
        sa.column("updated_at", sa.DateTime),
    )
    now = datetime.now(UTC)
    op.bulk_insert(
        categories_table,
        [
            {
                "name": cat_name,
                "is_default": True,
                "created_at": now,
                "updated_at": now,
            }
            for cat_name in default_categories
        ],
    )

    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("avatar", sa.String(length=500), nullable=True),
        sa.Column("password", sa.String(length=255), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_created_at"), "users", ["created_at"], unique=False)
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_index(op.f("ix_users_updated_at"), "users", ["updated_at"], unique=False)
    op.create_table(
        "groups",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("owner_id", sa.Integer(), nullable=False),
        sa.Column("created_by_id", sa.Integer(), nullable=True),
        sa.Column("updated_by_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["updated_by_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_groups_created_at"), "groups", ["created_at"], unique=False)
    op.create_index(op.f("ix_groups_created_by_id"), "groups", ["created_by_id"], unique=False)
    op.create_index(op.f("ix_groups_owner_id"), "groups", ["owner_id"], unique=False)
    op.create_index(op.f("ix_groups_updated_at"), "groups", ["updated_at"], unique=False)
    op.create_index(op.f("ix_groups_updated_by_id"), "groups", ["updated_by_id"], unique=False)
    op.create_table(
        "refresh_tokens",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("token", sa.String(length=64), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("device_info", sa.String(length=255), nullable=True),
        sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_revoked", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_refresh_token_token", "refresh_tokens", ["token"], unique=False)
    op.create_index("ix_refresh_token_user_expires", "refresh_tokens", ["user_id", "expires_at"], unique=False)
    op.create_index("ix_refresh_token_user_revoked", "refresh_tokens", ["user_id", "is_revoked"], unique=False)
    op.create_index(op.f("ix_refresh_tokens_created_at"), "refresh_tokens", ["created_at"], unique=False)
    op.create_index(op.f("ix_refresh_tokens_expires_at"), "refresh_tokens", ["expires_at"], unique=False)
    op.create_index(op.f("ix_refresh_tokens_is_revoked"), "refresh_tokens", ["is_revoked"], unique=False)
    op.create_index(op.f("ix_refresh_tokens_token"), "refresh_tokens", ["token"], unique=True)
    op.create_index(op.f("ix_refresh_tokens_updated_at"), "refresh_tokens", ["updated_at"], unique=False)
    op.create_index(op.f("ix_refresh_tokens_user_id"), "refresh_tokens", ["user_id"], unique=False)
    op.create_table(
        "group_users",
        sa.Column("group_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("created_by_id", sa.Integer(), nullable=True),
        sa.Column("updated_by_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["group_id"],
            ["groups.id"],
        ),
        sa.ForeignKeyConstraint(
            ["updated_by_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("group_id", "user_id"),
    )
    op.create_index(op.f("ix_group_users_created_at"), "group_users", ["created_at"], unique=False)
    op.create_index(op.f("ix_group_users_created_by_id"), "group_users", ["created_by_id"], unique=False)
    op.create_index(op.f("ix_group_users_updated_at"), "group_users", ["updated_at"], unique=False)
    op.create_index(op.f("ix_group_users_updated_by_id"), "group_users", ["updated_by_id"], unique=False)
    op.create_table(
        "periods",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("group_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("start_date", sa.DateTime(timezone=True), nullable=False),
        sa.Column("end_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_settled", sa.Boolean(), nullable=False),
        sa.Column("settled_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_by_id", sa.Integer(), nullable=True),
        sa.Column("updated_by_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["group_id"],
            ["groups.id"],
        ),
        sa.ForeignKeyConstraint(
            ["updated_by_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_period_group_dates", "periods", ["group_id", "start_date", "end_date"], unique=False)
    op.create_index("ix_period_group_settled", "periods", ["group_id", "is_settled"], unique=False)
    op.create_index(op.f("ix_periods_created_at"), "periods", ["created_at"], unique=False)
    op.create_index(op.f("ix_periods_created_by_id"), "periods", ["created_by_id"], unique=False)
    op.create_index(op.f("ix_periods_group_id"), "periods", ["group_id"], unique=False)
    op.create_index(op.f("ix_periods_updated_at"), "periods", ["updated_at"], unique=False)
    op.create_index(op.f("ix_periods_updated_by_id"), "periods", ["updated_by_id"], unique=False)
    op.create_table(
        "transactions",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("transaction_kind", sa.String(length=50), nullable=False),
        sa.Column("split_kind", sa.String(length=20), nullable=False),
        sa.Column("description", sa.String(length=1000), nullable=True),
        sa.Column("amount", sa.Integer(), nullable=False),
        sa.Column("payer_id", sa.Integer(), nullable=False),
        sa.Column("category_id", sa.Integer(), nullable=False),
        sa.Column("period_id", sa.Integer(), nullable=False),
        sa.Column("created_by_id", sa.Integer(), nullable=True),
        sa.Column("updated_by_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["categories.id"],
        ),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["payer_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["period_id"],
            ["periods.id"],
        ),
        sa.ForeignKeyConstraint(
            ["updated_by_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_transaction_period_created", "transactions", ["period_id", "created_at"], unique=False)
    op.create_index("ix_transaction_period_payer", "transactions", ["period_id", "payer_id"], unique=False)
    op.create_index(op.f("ix_transactions_category_id"), "transactions", ["category_id"], unique=False)
    op.create_index(op.f("ix_transactions_created_at"), "transactions", ["created_at"], unique=False)
    op.create_index(op.f("ix_transactions_created_by_id"), "transactions", ["created_by_id"], unique=False)
    op.create_index(op.f("ix_transactions_payer_id"), "transactions", ["payer_id"], unique=False)
    op.create_index(op.f("ix_transactions_period_id"), "transactions", ["period_id"], unique=False)
    op.create_index(op.f("ix_transactions_updated_at"), "transactions", ["updated_at"], unique=False)
    op.create_index(op.f("ix_transactions_updated_by_id"), "transactions", ["updated_by_id"], unique=False)
    op.create_table(
        "expense_shares",
        sa.Column("transaction_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("share_amount", sa.Integer(), nullable=True),
        sa.Column("share_percentage", sa.Float(), nullable=True),
        sa.Column("created_by_id", sa.Integer(), nullable=True),
        sa.Column("updated_by_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["transaction_id"],
            ["transactions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["updated_by_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("transaction_id", "user_id"),
    )
    op.create_index(op.f("ix_expense_shares_created_at"), "expense_shares", ["created_at"], unique=False)
    op.create_index(op.f("ix_expense_shares_created_by_id"), "expense_shares", ["created_by_id"], unique=False)
    op.create_index(op.f("ix_expense_shares_transaction_id"), "expense_shares", ["transaction_id"], unique=False)
    op.create_index(op.f("ix_expense_shares_updated_at"), "expense_shares", ["updated_at"], unique=False)
    op.create_index(op.f("ix_expense_shares_updated_by_id"), "expense_shares", ["updated_by_id"], unique=False)
    op.create_index(op.f("ix_expense_shares_user_id"), "expense_shares", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_expense_shares_user_id"), table_name="expense_shares")
    op.drop_index(op.f("ix_expense_shares_updated_by_id"), table_name="expense_shares")
    op.drop_index(op.f("ix_expense_shares_updated_at"), table_name="expense_shares")
    op.drop_index(op.f("ix_expense_shares_transaction_id"), table_name="expense_shares")
    op.drop_index(op.f("ix_expense_shares_created_by_id"), table_name="expense_shares")
    op.drop_index(op.f("ix_expense_shares_created_at"), table_name="expense_shares")
    op.drop_table("expense_shares")
    op.drop_index(op.f("ix_transactions_updated_by_id"), table_name="transactions")
    op.drop_index(op.f("ix_transactions_updated_at"), table_name="transactions")
    op.drop_index(op.f("ix_transactions_period_id"), table_name="transactions")
    op.drop_index(op.f("ix_transactions_payer_id"), table_name="transactions")
    op.drop_index(op.f("ix_transactions_created_by_id"), table_name="transactions")
    op.drop_index(op.f("ix_transactions_created_at"), table_name="transactions")
    op.drop_index(op.f("ix_transactions_category_id"), table_name="transactions")
    op.drop_index("ix_transaction_period_payer", table_name="transactions")
    op.drop_index("ix_transaction_period_created", table_name="transactions")
    op.drop_table("transactions")
    op.drop_index(op.f("ix_periods_updated_by_id"), table_name="periods")
    op.drop_index(op.f("ix_periods_updated_at"), table_name="periods")
    op.drop_index(op.f("ix_periods_group_id"), table_name="periods")
    op.drop_index(op.f("ix_periods_created_by_id"), table_name="periods")
    op.drop_index(op.f("ix_periods_created_at"), table_name="periods")
    op.drop_index("ix_period_group_settled", table_name="periods")
    op.drop_index("ix_period_group_dates", table_name="periods")
    op.drop_table("periods")
    op.drop_index(op.f("ix_group_users_updated_by_id"), table_name="group_users")
    op.drop_index(op.f("ix_group_users_updated_at"), table_name="group_users")
    op.drop_index(op.f("ix_group_users_created_by_id"), table_name="group_users")
    op.drop_index(op.f("ix_group_users_created_at"), table_name="group_users")
    op.drop_table("group_users")
    op.drop_index(op.f("ix_refresh_tokens_user_id"), table_name="refresh_tokens")
    op.drop_index(op.f("ix_refresh_tokens_updated_at"), table_name="refresh_tokens")
    op.drop_index(op.f("ix_refresh_tokens_token"), table_name="refresh_tokens")
    op.drop_index(op.f("ix_refresh_tokens_is_revoked"), table_name="refresh_tokens")
    op.drop_index(op.f("ix_refresh_tokens_expires_at"), table_name="refresh_tokens")
    op.drop_index(op.f("ix_refresh_tokens_created_at"), table_name="refresh_tokens")
    op.drop_index("ix_refresh_token_user_revoked", table_name="refresh_tokens")
    op.drop_index("ix_refresh_token_user_expires", table_name="refresh_tokens")
    op.drop_index("ix_refresh_token_token", table_name="refresh_tokens")
    op.drop_table("refresh_tokens")
    op.drop_index(op.f("ix_groups_updated_by_id"), table_name="groups")
    op.drop_index(op.f("ix_groups_updated_at"), table_name="groups")
    op.drop_index(op.f("ix_groups_owner_id"), table_name="groups")
    op.drop_index(op.f("ix_groups_created_by_id"), table_name="groups")
    op.drop_index(op.f("ix_groups_created_at"), table_name="groups")
    op.drop_table("groups")
    op.drop_index(op.f("ix_users_updated_at"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_index(op.f("ix_users_created_at"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_categories_updated_at"), table_name="categories")
    op.drop_index(op.f("ix_categories_name"), table_name="categories")
    op.drop_index(op.f("ix_categories_created_at"), table_name="categories")
    op.drop_table("categories")
    # ### end Alembic commands ###
